MODEL:
  META_ARCHITECTURE: "DQRF_DETR"
  WEIGHTS: "./detectron2/ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]
  BACKBONE:
    FREEZE_AT: 2 # FREEZE STEM + block 1
    NAME: "build_resnet_backbone"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "FrozenBN"
    OUT_FEATURES: ["res3", "res4", "res5"]
  DQRF_DETR:
    AUX_LOSS: False
    NUM_CLASSES: 1
    NUM_QUERIES: 300
    DENSE_QUERY: False
    RECTIFIED_ATTENTION: True

INPUT:
  MIN_SIZE_TRAIN: (800, )
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1400
  MAX_SIZE_TEST: 1400
  FORMAT: "BGR"
  
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4

DATASETS:
  TRAIN: ("crowdhuman_train",)
  TEST: ("crowdhuman_val",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.00004
  STEPS: (150000,) # 15000 // 4 * 40
  GAMMA: 0.1
  MAX_ITER: 187500
  CHECKPOINT_PERIOD: 8000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  SAMPLE_MULTIPLIER: 0.1
  CENTER_MULTPLIER: 0.1
  WEIGHT_MULTIPLIER: 1.0

TEST: 
  EVAL_PERIOD: 3750
  EVAL_START: 75000
  DETECTIONS_PER_IMAGE: 200
SEED: 11301416
OUTPUT_DIR: "./data/model/crowdhuman/dqrf_detr_baseline"

VERSION: 2