_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "./detectron2/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x] for x in [32, 64, 128, 256, 512 ]]"]
    ASPECT_RATIOS: [[1.0]]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 2
  ALLOW_BOX_OUT_OF_BOUNDARY: True
  FPN:
    NORM: "BN"
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1400
  MAX_SIZE_TEST: 1400
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
DATASETS:
  TRAIN: ("crowdhuman_train",)
  TEST: ("crowdhuman_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0025
  STEPS: (18750, 24375)
  MAX_ITER: 28125
  CHECKPOINT_PERIOD: 4000
  WARMUP_ITERS: 800
  WARMUP_FACTOR: 0.1
TEST:
  EVAL_PERIOD: 1000
  EVAL_START: 12000
  DETECTIONS_PER_IMAGE: 200
SEED: 11301415
OUTPUT_DIR: "./data/model/crowdhuman/retinanet_R_50_FPN_baseline_iou0.5"
# 
