_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "./detectron2/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x] for x in [32, 64, 128, 256, 512 ]]"]
    ASPECT_RATIOS: [[1.0]]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 2
  ALLOW_BOX_OUT_OF_BOUNDARY: True
  FPN:
    NORM: "BN"
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1400
  MAX_SIZE_TEST: 1400
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
DATASETS:
  TRAIN: ("crowdhuman_train",)
  TEST: ("crowdhuman_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (75000, 97500)
  MAX_ITER: 112500
  CHECKPOINT_PERIOD: 8000
  WARMUP_ITERS: 3200
  WARMUP_FACTOR: 0.1
TEST:
  EVAL_PERIOD: 3750
  EVAL_START: 60000
  DETECTIONS_PER_IMAGE: 200
SEED: 11301415
OUTPUT_DIR: "./data/model/crowdhuman/retinanet_R_50_FPN_baseline_iou0.5"
# 
